export const STRINGS = {
  appTitle: 'Falling Blocks',
  appSubtitle: 'inspired by tetris',
  tagline:
    'Left hand moves the block. Open → close to rotate. With a second hand, swipe down to fall faster.',
  loadingCamera: 'Starting camera…',
  loadingHand: 'Loading hand tracking…',
  loadingModel: 'Loading hand model…',
  cameraDenied: 'Camera access denied. Allow camera to play.',
  cameraError: 'Could not start camera.',
  cameraApiError: 'Camera not supported in this browser.',
  cameraNoSize: 'Camera has no video size.',
  cameraVideoError: 'Camera video error.',
  cameraTimeout: 'Camera timed out.',
  start: 'Roll Camera',
  calibrate: 'Hold your hand in frame…',
  calibrateHint: 'Show your open palm to the camera',
  ready: 'Tracking',
  openPalm: 'Hand open — close to rotate',
  fist: 'Hand closed',
  rotateHint: 'Open → close to rotate',
  softDrop: 'Fast fall',
  softDropHint: 'Other hand: swipe down',
  noHand: 'Hand lost — show palm to control',
  score: 'Score',
  lines: 'Lines',
  level: 'Level',
  gameOver: 'CUT TO BLACK',
  gameOverSub: 'The stack reached the top',
  retry: 'Take Two',
  introCountdown: ['3', '2', '1', 'ACTION'],
  backToHome: 'All Games',
}
