export const STRINGS = {
  appTitle: 'Cinematic Hand Snake',
  tagline: 'Your finger is the head. The tail follows.',
  loadingCamera: 'Starting camera…',
  loadingHand: 'Loading hand tracking…',
  loadingModel: 'Loading hand model…',
  cameraDenied: 'Camera access denied. Allow camera to play.',
  cameraError: 'Could not start camera.',
  cameraApiError: 'Camera not supported in this browser.',
  cameraNoSize: 'Camera has no video size.',
  cameraVideoError: 'Camera video error.',
  cameraTimeout: 'Camera timed out.',
  start: 'Roll Camera',
  calibrate: 'Hold your hand in frame…',
  calibrateHint: 'Show your index finger to the camera',
  ready: 'Tracking',
  action: 'ACTION',
  level: 'Level',
  score: 'Score',
  food: 'Food',
  gameOver: 'CUT TO BLACK',
  gameOverSub: 'You collided with your own trail',
  retry: 'Take Two',
  levelComplete: 'SCENE COMPLETE',
  nextLevel: 'Next reel rolling…',
  noHand: 'Hand lost — hold finger visible',
  introCountdown: ['3', '2', '1', 'ACTION'],
  backToHome: 'All Games',
}
