export const STRINGS = {
  appTitle: 'Light Painter',
  appSubtitle: 'Male mit Licht!',
  tagline: 'Zeige mit dem Finger auf die Kamera und male leuchtende Bilder in die Luft.',
  introHint: 'Zeigefinger ausstrecken = malen · Hand öffnen = Pause',
  start: 'Los geht’s!',

  loadingCamera: 'Kamera startet…',
  loadingHand: 'Handzauber wird geladen…',
  loadingModel: 'Zauberstift wird vorbereitet…',
  cameraDenied: 'Kamera nicht erlaubt. Bitte Kamera freigeben, um zu malen.',
  cameraError: 'Die Kamera konnte nicht starten.',
  cameraApiError: 'Dieser Browser unterstützt keine Kamera.',
  cameraNoSize: 'Die Kamera liefert kein Bild.',
  cameraVideoError: 'Kamera-Fehler.',
  cameraTimeout: 'Die Kamera braucht zu lange.',

  modeTitle: 'Was möchtest du malen?',
  modeFreeTitle: 'Freies Malen',
  modeFreeDesc: 'Male, was du willst – mit leuchtenden Farben!',
  modeTraceTitle: 'Nachmalen',
  modeTraceDesc: 'Male die Vorlage nach und sammle Sterne!',
  templatePickTitle: 'Such dir eine Vorlage aus!',
  shapesTab: 'Formen',
  lettersTab: 'Buchstaben',

  toolbarColors: 'Farbe',
  toolbarWidth: 'Strichdicke',
  toolbarGlow: 'Glühen',
  toolbarFade: 'Magic Fade',
  toolbarBackground: 'Hintergrund',
  bgNight: 'Nachthimmel (Kamera klein)',
  bgCamera: 'Kamera als Hintergrund',
  clear: 'Alles löschen',
  save: 'Bild speichern',
  back: 'Zurück',
  changeTemplate: 'Vorlage wechseln',

  noHand: 'Zeig deine Hand!',
  penUp: 'Zeigefinger ausstrecken zum Malen',
  drawing: 'Du malst!',

  traceProgress: 'Schon {percent} % geschafft!',
  successTitle: 'Geschafft!',
  successSub: 'Du hast die Vorlage super nachgemalt!',
  successAgain: 'Nochmal',
  successNext: 'Nächste Vorlage',
  successFree: 'Frei weitermalen',

  backToHome: 'Alle Spiele',
  saveFileName: 'lightpainter-bild.png',
}
