export const STRINGS = {
  appTitle: 'Cinematic Hand Pacman',
  tagline: 'Point your finger — Pacman follows the direction.',
  loadingHand: 'Loading hand tracking…',
  start: 'Roll Camera',
  calibrate: 'Hold your hand in frame…',
  calibrateHint: 'Show your index finger to the camera',
  ready: 'Tracking',
  level: 'Level',
  score: 'Score',
  pellets: 'Pellets',
  gameOver: 'CUT TO BLACK',
  gameOverGhost: 'A ghost caught you',
  gameOverHand: 'Hand lost — hold finger visible',
  retry: 'Take Two',
  levelComplete: 'MAZE CLEAR',
  nextLevel: 'Next reel rolling…',
  noHand: 'Hand lost — hold finger visible',
  introCountdown: ['3', '2', '1', 'ACTION'],
  backToHome: 'All Games',
  powerMode: 'POWER!',
}
