export const STRINGS = {
  title: 'HAND SHOOTER',
  tagline: 'Webcam · Hand tracking',
  subtitle:
    'Aim with your index fingertip and shoot by pinching thumb and index finger together. Moorhuhn-inspired — powered by your webcam.',
  startGame: 'START GAME',
  calibrate: 'Calibration',
  calibrateHint:
    'Hold your hand in frame — index finger aims, thumb + index pinch = shoot.',
  skipCalibrate: 'Skip (Space)',
  scoreLabel: 'SCORE',
  hitsLabel: 'HITS',
  shotsLabel: 'SHOTS',
  accuracyLabel: 'ACCURACY',
  ready: 'Ready',
  fired: 'Bang!',
  pinchHint: 'Pinch = shoot',
  pinchOverlay: 'FIRE',
  cameraDenied: 'Camera blocked — allow access in your browser.',
  cameraError: 'Camera unavailable — use HTTPS or localhost.',
  cameraApiError: 'Camera API unavailable — use HTTPS or localhost.',
  cameraNoSize: 'Camera returned no image.',
  cameraVideoError: 'Camera preview failed.',
  cameraTimeout: 'Camera timeout — check permissions.',
  loadingHand: 'Loading camera & hand model…',
  loadingModel: 'Loading hand model…',
  loadingCamera: 'Loading camera…',
  layoutFullscreen: 'Fullscreen',
  layoutSplit: 'Split view',
  restart: 'Restart',
  arenaLabel: 'Shooter arena',
  backToHome: 'All Games',
}
